### ISSUE TITLE
investigate API performance issues

### ISSUE THREAD

**Issue by MMisery** [sc3/cookcountyjail#88]
When accessing http://cookcountyjail.recoveredfactory.net/api/1.0/countyinmate/?format=json&limit=0&related=1 in the browser, a 504 is thrown after roughly 4 minutes (240157 ms) of trying to fetch the data. Below is a screenshot of the problem. It was suggested that the cause of the problem may be a bad join (within the query) with the related information.
![nginx_timout](https://f.cloud.github.com/assets/3255057/867529/951e8f94-f706-11e2-89dd-90e1689e5f24.png)

**Comment by bepetersn** [comment]
I have reproduced this error by a different means. When querying all five of our APIs (countyinmate, courtlocation, housinglocation, courtdate, and housinghistory) in a row with a 'limit'=0 param, I got this error only on the last two. 

One thought I have is that both of these (courtdate and housinghistory) have to do foreign key lookup, whereas the other three do not. For instance, CourtDate objects have fields for a CountyInmate object and a CourtLocation object. Perhaps... our server is not good at querying its own API while being queried? The definition of 504 error is: "The server acting as a gateway or proxy and did not receive a timely response from the upstream server." In other words, it's strictly a timeout error for our upstream server, Gunicorn in this case.

**Comment by nwinklareth** [comment]
Brain,

Have you tried the last two calls by themselves?

Would also please include the calls you making in the your as well?

Norbert

On Tue, Jul 30, 2013 at 7:09 PM, Brian Peterson notifications@github.comwrote:

> I have reproduced this error by a different means. When querying all five
> of our APIs (countyinmate, courtlocation, housinglocation, courtdate, and
> housinghistory) in a row with a 'limit'=0 param, I got this error only on
> the last two.
> 
> One thought I have is that both of these (courtdate and housinghistory)
> have to do foreign key lookup, whereas the other three do not. That is,
> CourtDate objects have fields for a CountyInmate object and a CourtLocation
> object. Perhaps... our server is not good at querying its own API while
> being queried? The definition of 504 error is: "The server was acting as a
> gateway or proxy and did not receive a timely response from the upstream
> server."
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/88#issuecomment-21832199
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
I can confirm courtdate API endpoint fails by itself with limit=0. Note
that it doesn't fail if you don't ask for everything. I've tried as much as
1000 and it gave me the data.

**Comment by eads** [comment]
I can weigh in on this a little later, I have some insight to share

**Comment by eads** [comment]
Okay, so this is a fun one. I did some profiling of Tastypie back in Feb to
address our perennial performance problems. I thought at first it was
because we weren't doing JOINs but instead querying for every record. So I
fixed that, but the mofo still ran slow. It turns out getting the whole
record set, joins and all is on the order of a few seconds. I found
Tastypie is the culprit: to allow for tons of post processing flexibility,
Tastypie loops through, like, everything. And to provide Unicode output
Tastypie encodes every record which turns out to be crazily slow. I
actually added the "related" flag precisely to cut down on processing time
to get results back before the gateway timeout.

It's tough: Tastypie is amazing and handy and useful but I suspect and fear
that as we hone in on useful summary API endpoints it will make more sense
to write our own system. But best case in my mind is helping learn how to
make Tastypie support efficient delivery of big datasets as well as small.

**Comment by nwinklareth** [comment]
Why don't we start by converting the database to use utf-8 and then convert
all of the data in it to utf-8, wouldn't that avoid the tastypie conversion
problem?

Also is it possible that tastypie 0.9.16 might handle this better 0.9.14 we
are currently running?

Norbert

On Tue, Jul 30, 2013 at 7:54 PM, David Eads notifications@github.comwrote:

> Okay, so this is a fun one. I did some profiling of Tastypie back in Feb to
> address our perennial performance problems. I thought at first it was
> because we weren't doing JOINs but instead querying for every record. So I
> fixed that, but the mofo still ran slow. It turns out getting the whole
> record set, joins and all is on the order of a few seconds. I found
> Tastypie is the culprit: to allow for tons of post processing flexibility,
> Tastypie loops through, like, everything. And to provide Unicode output
> Tastypie encodes every record which turns out to be crazily slow. I
> actually added the "related" flag precisely to cut down on processing time
> to get results back before the gateway timeout.
> 
> It's tough: Tastypie is amazing and handy and useful but I suspect and fear
> that as we hone in on useful summary API endpoints it will make more sense
> to write our own system. But best case in my mind is helping learn how to
> make Tastypie support efficient delivery of big datasets as well as small.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/88#issuecomment-21833786
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by eads** [comment]
Converting the db to UTF might help if Tastypie is smart enough to skip the
encoding in that case.

We should try upgrading, though I thought 0.9.15 was latest stable version.
IIRC 0.9.14 put in a major performance improvement related to object
copying. I will check on that.

**Comment by bepetersn** [comment]
That sounds like a good idea, Norbert. I'm not sure, but I think converting to utf-8 should be pretty trivial.

**Comment by bepetersn** [comment]
The original behavior described by @MMisery still appears to happen.

**Comment by eads** [comment]
Tastypie just dunnae hae the powah, captain.

**Comment by bepetersn** [comment]
Does Flask-Restless? Or some other extant solution?

... You don't have to answer that question.

**Comment by eads** [comment]
There's a bunch of ways to deal with it. First -- update tastypie, they
have made major improvements.

Tastypie is just so dang handy. But the string encoding kills ya on large
datasets. Norbert had suggested we patch it to drop the encoding step and
just use the right encoding at the db layer. We may have to explore that at
the Trib anyway for our crime site.

**Comment by nwinklareth** [comment]
Perhaps tastypie has gotten smarter and does not do Unicode encoding
especially given that the database entries are in utf-8

On Wed, Feb 26, 2014 at 6:59 PM, David Eads notifications@github.comwrote:

> There's a bunch of ways to deal with it. First -- update tastypie, they
> have made major improvements.
> 
> Tastypie is just so dang handy. But the string encoding kills ya on large
> datasets. Norbert had suggested we patch it to drop the encoding step and
> just use the right encoding at the db layer. We may have to explore that at
> the Trib anyway for our crime site.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/88#issuecomment-36198337
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
Did we make that change? I was going to say I'm perfectly willing to look
into fixing it.

**Comment by nwinklareth** [comment]
I thought that the last time I looked at values from the database they were
utf-8 encoded.

On Wed, Feb 26, 2014 at 7:30 PM, Brian Everett Peterson <
notifications@github.com> wrote:

> Did we make that change? I was going to say I'm perfectly willing to look
> into fixing it.
> 
> On Feb 26, 2014 7:26 PM, "nwinklareth" notifications@github.com wrote:
> 
> > Perhaps tastypie has gotten smarter and does not do Unicode encoding
> > especially given that the database entries are in utf-8
> > 
> > On Wed, Feb 26, 2014 at 6:59 PM, David Eads <notifications@github.com
> > 
> > > wrote:
> > > 
> > > There's a bunch of ways to deal with it. First -- update tastypie, they
> > > have made major improvements.
> > > 
> > > Tastypie is just so dang handy. But the string encoding kills ya on
> > > large
> > > datasets. Norbert had suggested we patch it to drop the encoding step
> > > and
> > > just use the right encoding at the db layer. We may have to explore
> > > that
> > > at
> > > the Trib anyway for our crime site.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/sc3/cookcountyjail/issues/88#issuecomment-36198337>
> > > 
> > > .
> > 
> > ## 
> > 
> > Regards
> > 
> > ## Norbert
> > 
> > Norbert Winklareth
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/cookcountyjail/issues/88#issuecomment-36200117>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/88#issuecomment-36200390
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
Confirmed that all the strings in the DB are utf-8 encoded. I've just updated tastypie to the very latest version, we were only behind a little bit, and their changes for the last iteration don't mention anything having to do with unicode or performance from what I can tell. 

Going off of what @eads said awhile back regarding django-tastypie and unicode, I'm gonna browse their code a bit and see what I can see in regards to encodings.
